In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
# Cargar archivo registro arduino y encontrar tiempo en ms y banderas
fn_reg = r'C:\Users\neuro\OneDrive\Documentos\Nicole\BTBR_GCaMP6\BTBR_R2_HEMBRA_PASIVA_27-09-2023\BTBR_R2_HEMBRA_PASIVA_reg122535.txt'
with open(fn_reg, 'r') as file:
    C = file.readlines()
C

['12:25:35.745.0.0\n',
 '12:25:45.838101.9172.23.1\n',
 '12:25:45.846356.9174.23.1\n',
 '12:25:45.859163.9174.23.1\n',
 '12:25:45.871734.9174.23.1\n',
 '12:25:45.883779.9175.23.1\n',
 '12:25:45.896027.9175.23.1\n',
 '12:25:45.904302.9176.23.1\n',
 '12:25:46.035395.9370.23.1\n',
 '12:25:46.046962.9370.23.1\n',
 '12:25:46.055942.9371.23.1\n',
 '12:25:46.067926.9371.23.1\n',
 '12:25:46.079844.9372.23.1\n',
 '12:25:46.092929.9372.23.1\n',
 '12:25:46.104597.9372.23.1\n',
 '12:25:46.232243.9568.23.1\n',
 '12:25:46.244251.9568.23.1\n',
 '12:25:46.256547.9568.23.1\n',
 '12:25:46.264738.9569.23.1\n',
 '12:25:46.276940.9569.23.1\n',
 '12:25:46.289317.9570.23.1\n',
 '12:25:46.301590.9570.23.1\n',
 '12:25:46.428568.9764.23.1\n',
 '12:25:46.440448.9765.23.1\n',
 '12:25:46.452644.9765.23.1\n',
 '12:25:46.465126.9766.23.1\n',
 '12:25:46.473575.9766.23.1\n',
 '12:25:46.485649.9766.23.1\n',
 '12:25:46.497616.9767.23.1\n',
 '12:25:46.624583.9962.23.1\n',
 '12:25:46.637460.9962.23.1\n',
 '12:25:46.649210

In [3]:
# Procesar las líneas del archivo
datasplit = [line.split('.') for line in C[1:]]  # Split lines starting from the second line
timestamp_flgs = [str(item[0]) for item in datasplit]
millisec = np.array([float(item[2]) for item in datasplit])
sensores = np.array([float(item[3]) for item in datasplit])
print(millisec)
print(sensores)

[  9172.   9174.   9174. ... 862339. 862535. 862535.]
[23. 23. 23. ... 23. 23. 23.]


In [4]:
# Encontrar banderas únicas y contar ocurrencias
flags, counts = np.unique(sensores, return_counts=True)
value_counts = np.column_stack((flags, counts))
print(value_counts)

[[2.0000e+00 1.8700e+02]
 [4.0000e+00 1.9100e+02]
 [2.3000e+01 2.6052e+04]]


In [5]:
# Cargar archivo registro psychopy y encontrar estímulos
fn_log = r'C:\Users\neuro\OneDrive\Documentos\Nicole\BTBR_GCaMP6\BTBR_R2_HEMBRA_PASIVA_27-09-2023\BTBR_R2_HEMBRA_PASIVA_log122548.txt'
with open(fn_log, 'r') as file:
    C_log = file.readlines()
C_log

['12:25:57.911.11\n',
 '12:26:02.089.045\n',
 '12:26:10.227.11\n',
 '12:26:14.408.0135\n',
 '12:26:22.548.11\n',
 '12:26:26.726.0315\n',
 '12:26:34.863.11\n',
 '12:26:39.044.0225\n',
 '12:26:47.183.11\n',
 '12:26:51.363.090\n',
 '12:26:59.502.11\n',
 '12:27:03.682.0180\n',
 '12:27:11.821.11\n',
 '12:27:16.000.00\n',
 '12:27:24.138.11\n',
 '12:27:28.318.0270\n',
 '12:27:36.455.11\n',
 '12:27:44.435.11\n',
 '12:27:48.611.0180\n',
 '12:27:56.751.11\n',
 '12:28:00.930.045\n',
 '12:28:09.070.11\n',
 '12:28:13.249.0315\n',
 '12:28:21.387.11\n',
 '12:28:25.566.0225\n',
 '12:28:33.705.11\n',
 '12:28:37.885.0270\n',
 '12:28:46.022.11\n',
 '12:28:50.203.0135\n',
 '12:28:58.340.11\n',
 '12:29:02.521.00\n',
 '12:29:10.659.11\n',
 '12:29:14.840.090\n',
 '12:29:22.977.11\n',
 '12:29:30.953.11\n',
 '12:29:35.133.0315\n',
 '12:29:43.271.11\n',
 '12:29:47.451.0180\n',
 '12:29:55.587.11\n',
 '12:29:59.769.00\n',
 '12:30:07.906.11\n',
 '12:30:12.130.0225\n',
 '12:30:20.269.11\n',
 '12:30:24.455.045\n',
 

In [6]:
# Procesar las líneas del archivo de psychopy
datasplit_log = [line.split('.') for line in C_log]
tstamp_stlog = [str(item[0]) for item in datasplit_log]
estimulos = np.array([float(item[2]) for item in datasplit_log])

In [7]:
# Obtener identidades únicas de cada estímulo
stims, stim_counts = np.unique(estimulos, return_counts=True)
value_counts_st = np.column_stack((stims, stim_counts))
print(stims)

[  0.  11.  45.  90. 135. 180. 225. 270. 315.]


In [8]:
# Filtrar estímulos
stims = stims[stims != 11]
# Convertir a entero el valor usado para definir la dimensión del array
idx_t_stim = np.zeros((int(value_counts_st[0, 1]), len(stims)))
print(stims)

[  0.  45.  90. 135. 180. 225. 270. 315.]


In [9]:
for s, stim in enumerate(stims):
    t_stamp_idx = np.where(estimulos == stim)[0]
    t_stamp = [tstamp_stlog[i - 1] for i in t_stamp_idx]

    for j, ts in enumerate(t_stamp):
        hms = list(map(int, ts.split(':')))
        hms[2] += 1
        t_stamp2 = f"{hms[0]:02}:{hms[1]:02}:{hms[2]:02}"

        idx_timebin = np.concatenate((
            np.where(np.array(timestamp_flgs) == ts)[0],
            np.where(np.array(timestamp_flgs) == t_stamp2)[0]
        ))

        if len(idx_timebin) > 0:
            idx_stim_j = np.where(sensores[idx_timebin[0]:idx_timebin[-1]] == 4)[0] + idx_timebin[0]
            if len(idx_stim_j) > 0:
                idx_t_stim[j, s] = idx_stim_j[0]

print(t_stamp_idx)  # Para verificar el resultado

[  5  22  35  54  75  96 117 122]


In [14]:
# Alinear tiempo 0 a la adquisición del primer frame
millisec_f0 = millisec - millisec[0]

framt = np.where(sensores == 23)[0]
t_fram = millisec_f0[framt]
ll = np.diff(t_fram)
idx_t_fr = np.where(ll > 100)[0] + 1
t_fram_clean = np.insert(t_fram[idx_t_fr], 0, t_fram[0])
framt

array([    0,     1,     2, ..., 26427, 26428, 26429], dtype=int64)

In [11]:
# Encontrar frames en los que iniciaron los estímulos
t_Stimulus_ms = millisec_f0[idx_t_stim.astype(int)]
tf_stimulus = np.round(t_Stimulus_ms / 200).astype(int)
# Corrección del frame correcto
a = t_Stimulus_ms - t_fram_clean[tf_stimulus] > 200
idx_t_adj = np.where(a)[0]
tf_stimulus[idx_t_adj] += 1
print(tf_stimulus)

[[ 431   61  308  123  369  246  492  184]
 [ 963  655 1025  902  594  779  840  717]
 [1249 1373 1558 1496 1188 1311 1435 1126]
 [1906 2090 1967 2029 1782 1844 1659 1721]
 [2254 2438 2500 2561 2192 2315 2623 2376]
 [2909 3155 2724 2786 2971 3094 2847 3032]
 [3442 3627 3380 3318 3503 3257 3565 3688]
 [3913 3974 4036 4159 3790 4097 4221 3851]]


In [12]:
tf_stimulus=tf_stimulus.T
# Reshape stims to match idx_t_stim's rows
stims_reshaped = stims[:, np.newaxis]

# Create a 3D array by stacking stims_reshaped with idx_t_stim along a new axis
stimsnframes = np.stack([stims_reshaped] * tf_stimulus.shape[1], axis=1)

# Concatenate stimsnframes with idx_t_stim along the last axis
result = np.concatenate((stimsnframes, tf_stimulus[:, :, np.newaxis]), axis=2)

print(result.shape)  
print(result)

(8, 8, 2)
[[[   0.  431.]
  [   0.  963.]
  [   0. 1249.]
  [   0. 1906.]
  [   0. 2254.]
  [   0. 2909.]
  [   0. 3442.]
  [   0. 3913.]]

 [[  45.   61.]
  [  45.  655.]
  [  45. 1373.]
  [  45. 2090.]
  [  45. 2438.]
  [  45. 3155.]
  [  45. 3627.]
  [  45. 3974.]]

 [[  90.  308.]
  [  90. 1025.]
  [  90. 1558.]
  [  90. 1967.]
  [  90. 2500.]
  [  90. 2724.]
  [  90. 3380.]
  [  90. 4036.]]

 [[ 135.  123.]
  [ 135.  902.]
  [ 135. 1496.]
  [ 135. 2029.]
  [ 135. 2561.]
  [ 135. 2786.]
  [ 135. 3318.]
  [ 135. 4159.]]

 [[ 180.  369.]
  [ 180.  594.]
  [ 180. 1188.]
  [ 180. 1782.]
  [ 180. 2192.]
  [ 180. 2971.]
  [ 180. 3503.]
  [ 180. 3790.]]

 [[ 225.  246.]
  [ 225.  779.]
  [ 225. 1311.]
  [ 225. 1844.]
  [ 225. 2315.]
  [ 225. 3094.]
  [ 225. 3257.]
  [ 225. 4097.]]

 [[ 270.  492.]
  [ 270.  840.]
  [ 270. 1435.]
  [ 270. 1659.]
  [ 270. 2623.]
  [ 270. 2847.]
  [ 270. 3565.]
  [ 270. 4221.]]

 [[ 315.  184.]
  [ 315.  717.]
  [ 315. 1126.]
  [ 315. 1721.]
  [ 315. 2376.]


In [13]:
np.save('result.npy', result)